### ISSUE TITLE
Problems to run airbyte-module on OpenShift

### ISSUE THREAD

**Issue by roytman** [fybrik/airbyte-module#79]
When we [deployed](https://github.com/fybrik/airbyte-module/blob/main/fybrik/README_mysql.md#writing-dataset-with-fybrik-application) airbyte-module on OpenShift we have faced with a number of issues:

- The security context was not accepted by the OpenShift
- In order to run dind container, the pod has `privilege: true`  property, which was not acceptable by OpenShift.
- Without the `privilege: true`  property, the docker demon container cannot run.

**Comment by revit13** [comment]
[helm chart mysql deployment](https://github.com/fybrik/airbyte-module/blob/main/fybrik/README_mysql.md) also fails on openshift due to security context:

```    
 securityContext:
     fsGroup: 1001
